// Generated by https://quicktype.io

export interface RatesResponse {
    disclaimer: string;
    license:    string;
    timestamp:  number;
    base:       string;
    rates:      { [key: string]: number };
}
